version: '3.9'

services:
  konoz-backend-v2:
    image: araouf/konoz-backend:latest # Replace with your Docker Hub image
    ports:
      - "4000:4000" # Map container port to host port
    env_file:
      - .env # Path to your environment file
    restart: always # Automatically restart the container if it stops
